name: librarymanager
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Architecture
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Database (Local & Cloud)
  drift: ^2.23.1
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  path: ^1.9.1
  supabase_flutter: ^2.8.3

  # Hardware & AI
  camera: ^0.11.0+2
  http: ^1.2.0
  connectivity_plus: ^6.1.1
  workmanager: ^0.6.0-rc.3
  flutter_tesseract_ocr: ^0.4.30

  # UI & Utils
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  uuid: ^4.5.2
  go_router: ^17.0.1
  url_launcher: ^6.3.2
  fl_chart: ^1.1.1
  flutter_screenutil: ^5.9.3
  grouped_list: ^6.0.0
  calendar_date_picker2: ^2.0.1
  dotted_border: ^3.1.0
  timeago: ^3.7.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.0
  dio: ^5.9.0
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.7.2
  string_similarity: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.14
  drift_dev: ^2.23.1
  injectable_generator: ^2.6.3
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoapp.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/icon.png"
  android_12:
    image: "assets/images/icon.png"
    color: "#FFFFFF"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/tessdata/
    - assets/tessdata_config.json
